---
articles:
  - title: 天天惠来了，新的一周活动又开始了
    description: 天天惠活动每周一至周五火热进行中！！！
    url: http://m.wanliu.biz/daily_cheap/
    pic_url: https://mmbiz.qlogo.cn/mmbiz/b2AgUwueIgAicQ9stVLhEwgN5XOazHWQyoPpWd7k5LvjzDKNcbIrFCEwpGpkGSUGmibg8gFKGIzQI2tkFjKHNbQw/0?wx_fmt=jpeg

  - title: 六一活动圆满结束, 一共筹集￥551元
    description: 公益活动助力福利院小朋友节日快乐，你参与活动我们就送一块钱。
    url: http://m.wanliu.biz/one_money/2016-06-01/
    pic_url: https://mmbiz.qlogo.cn/mmbiz/b2AgUwueIgCqWbaQafWG9xVHQNiaG2q3TzF117bN2AUKic9XOcaJvdTrKPe42CnPITWyAA0ke2nb9XTzjp4pRraw/0?wx_fmt=jpeg

