#config/redis.yml
default: &default
  port: 6379

development:
  <<: *default
  host: localhost
test:
  <<: *default
  host: localhost
production:
  <<: *default
  host: <%= ENV['REDISDEV_PORT_6379_TCP_ADDR'] || ENV['REDISBETA_PORT_6379_TCP_ADDR'] || ENV['REDISDEVRC_PORT_6379_TCP_ADDR'] || 'localhost' %>
