app:
  website: http://m.wanliu.biz
  name: 万流网
  title: 万流电商社区
  footer: "&copy; Wanliu.biz 2015  湘ICP备：13005289号-1"
  keywords: "万流 电商 社区 O2O O2O2C B2C2C 母婴 奶粉"
  description:
  telephone: 0731-83991940
admin:
  title: 万流工作平台
  register:
    open: false
system:
  agent:
    id: 0
    username: system
    nickname: 系统小助理
    email: service@wanliu.biz
    mobile: 0734-83888168
    image:
      avatar_url: //static.wanliu.biz/images/logo.png
      preview_url: //static.wanliu.biz/images/logo.png
wanliu:
  backend: http://www.wanliu.biz/api/v1/
  pry_token: 87c87f8ef9699391e15202ca63cf1ebeb46314e04f2f6de002047c2f42ad57d936dc068888cb4e96c9be46b5bdb86de09fc5a00fce7092adf09f269d243af6c2
  subject_touch_token: cd74c43ecffc326040f9a314cf9d2e4afc534855bbf7a3c10a8486013e114ae97e69982de938839b4c21dd83fc27d18d3e002abedfc2c29b946e6ede69ac00e3
pusher:
  socket_host: www.wanliu.biz
  socket_port: 8000
  pusher_url: http://www.wanliu.biz:8000/api/v1/
  pusher_token: '3lfj8845fafda[f]fj394u983tioj5jtoi5j9hp;f4f9dfghr;nnbncxaf[fe;094t45g;jgih='
elasticsearch:
  url: http://192.168.0.131:9200
  index_name: products_production
assets:
  host: http://wanliu-piano.b0.upaiyun.com
  gray_image: "data:image/gif;base64,R0lGODlhAQABAIAAAMLCwgAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="
  avatar_image: "http://wanliu-piano.b0.upaiyun.com/uploads/shop/logo/1/default_avatar.gif"
  alliance_hosts:
    - 'http://neil-img.b0.upaiyun.com/'
shop:
  import:
    sale: true
  location:
    change_period: 7
  default_theme: theme1
  default_head_url: http://wanliu-piano.b0.upaiyun.com/uploads/shop/logo/1/20151207.jpg
dev:
  feature:
    weixin: true
    camera: true
    shop:
      website: false
    mobile:
      mini: true
    purchase: true
    cart: true
    favorites: false
    qrcode: true
    linkmen: true
    location: true
    order:
      chat: true
    user:
      sign_in: true
    industry: true
    weixin: true
    person_page: true
    to_be_supplier: false
job:
  async: open
sites:
  root: .sites
  shops:
    root: '.sites/shops'
  user:
    root: '.sites/users'
  system:
    root: '.sites/system'
GA:
  track: false
mail:
  sender: service@wanliu.biz
  address: smtp.ym.163.com
  port: 25
  user_name: service@wanliu.biz
  password: asdfasdf
  domain: http://m.wanliu.biz/
  url_host: http://m.wanliu.biz
  url_port: 80
baidu:
  ditu:
    secret: gUvTx8taqFAAD8PIN9TGacNG
after_registers:
  shop:
    validates: strict
  total:
    max_count: 15
  after_sign_in: false
  after_sign_in_path: after_registers
weixin:
  scope: snsapi_login
  after_sign_in: true
  after_sign_in_path: smart_fills
  regions: true
chat:
  display_username: true
  display_shopname: true
promotions:
  lock_timeout: 200
  one_money:
    timeout:
      minutes: 15
    ensure_url: http://m.wanliu.com/api/promotions/one_money/:id/ensure/:grab_id
    default:
      callback: http://m.wanliu.biz/orders/yiyuan_confirm
      fare: 10
