app:
  title: 万流电商社区
  footer: "&copy; Wanliu.biz 2015  湘ICP备：13005289号-1"
admin:
  title: 万流工作平台
system:
  agent:
    id: 0
    username: system
    nickname: 系统小助理
    email: service@wanliu.biz
    mobile: 0734-83888168
    image:
      avatar_url: //static.wanliu.biz/images/logo.png
      preview_url: //static.wanliu.biz/images/logo.png
wanliu:
  backend: http://www.wanliu.biz/api/v1/
pusher:
  socket_host: www.wanliu.biz
  socket_port: 8000
  pusher_url: http://www.wanliu.biz:8000/api/v1/
  pusher_token: '3lfj8845fafda[f]fj394u983tioj5jtoi5j9hp;f4f9dfghr;nnbncxaf[fe;094t45g;jgih='
