app:
  title: 万流电商社区
  footer: "&copy; Wanliu.biz 2015  湘ICP备：13005289号-1"
system:
  agent:
    id: 0
    username: system
    nickname: 系统小助理
    email: service@wanliu.biz
    mobile: 0734-83888168
    image: 
      avatar_url: //static.wanliu.biz/images/logo.png
      preview_url: //static.wanliu.biz/images/logo.png
wanliu: 
  backend: http://www.wanliu.biz/api/v1/
  socket_host: 192.168.0.155
  socket_port: 8000
