require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SalesMenController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # SalesMan. As you add validations to SalesMan, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SalesMenController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all sales_men as @sales_men" do
      sales_man = SalesMan.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:sales_men)).to eq([sales_man])
    end
  end

  describe "GET #show" do
    it "assigns the requested sales_man as @sales_man" do
      sales_man = SalesMan.create! valid_attributes
      get :show, {:id => sales_man.to_param}, valid_session
      expect(assigns(:sales_man)).to eq(sales_man)
    end
  end

  describe "GET #new" do
    it "assigns a new sales_man as @sales_man" do
      get :new, {}, valid_session
      expect(assigns(:sales_man)).to be_a_new(SalesMan)
    end
  end

  describe "GET #edit" do
    it "assigns the requested sales_man as @sales_man" do
      sales_man = SalesMan.create! valid_attributes
      get :edit, {:id => sales_man.to_param}, valid_session
      expect(assigns(:sales_man)).to eq(sales_man)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new SalesMan" do
        expect {
          post :create, {:sales_man => valid_attributes}, valid_session
        }.to change(SalesMan, :count).by(1)
      end

      it "assigns a newly created sales_man as @sales_man" do
        post :create, {:sales_man => valid_attributes}, valid_session
        expect(assigns(:sales_man)).to be_a(SalesMan)
        expect(assigns(:sales_man)).to be_persisted
      end

      it "redirects to the created sales_man" do
        post :create, {:sales_man => valid_attributes}, valid_session
        expect(response).to redirect_to(SalesMan.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved sales_man as @sales_man" do
        post :create, {:sales_man => invalid_attributes}, valid_session
        expect(assigns(:sales_man)).to be_a_new(SalesMan)
      end

      it "re-renders the 'new' template" do
        post :create, {:sales_man => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested sales_man" do
        sales_man = SalesMan.create! valid_attributes
        put :update, {:id => sales_man.to_param, :sales_man => new_attributes}, valid_session
        sales_man.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested sales_man as @sales_man" do
        sales_man = SalesMan.create! valid_attributes
        put :update, {:id => sales_man.to_param, :sales_man => valid_attributes}, valid_session
        expect(assigns(:sales_man)).to eq(sales_man)
      end

      it "redirects to the sales_man" do
        sales_man = SalesMan.create! valid_attributes
        put :update, {:id => sales_man.to_param, :sales_man => valid_attributes}, valid_session
        expect(response).to redirect_to(sales_man)
      end
    end

    context "with invalid params" do
      it "assigns the sales_man as @sales_man" do
        sales_man = SalesMan.create! valid_attributes
        put :update, {:id => sales_man.to_param, :sales_man => invalid_attributes}, valid_session
        expect(assigns(:sales_man)).to eq(sales_man)
      end

      it "re-renders the 'edit' template" do
        sales_man = SalesMan.create! valid_attributes
        put :update, {:id => sales_man.to_param, :sales_man => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested sales_man" do
      sales_man = SalesMan.create! valid_attributes
      expect {
        delete :destroy, {:id => sales_man.to_param}, valid_session
      }.to change(SalesMan, :count).by(-1)
    end

    it "redirects to the sales_men list" do
      sales_man = SalesMan.create! valid_attributes
      delete :destroy, {:id => sales_man.to_param}, valid_session
      expect(response).to redirect_to(sales_men_url)
    end
  end

end
